config/routes.rb
YEAR_MONTH_REQUIREMENTS = {:year => /[0-9]*|_YEAR_/, :month => /[1-9]|10|11|12|_MONTH_/}

Rails.application.routes.draw do

  namespace :settings do
    controller :accounts do
      %w(asset income expense).each do |type|
        with_options account_type: type do |with_type|
          with_type.put type.pluralize, :action => :update_all
          with_type.resources type.pluralize, controller: :accounts, only: [:index, :show, :create, :update, :destroy]
        end
      end
    end

    resources :account_link_requests, :path => 'accounts/:account_id/link_requests', :only => [:destroy]

    scope :controller => :account_links, :path => 'accounts' do
      scope :path => ':account_id' do
        resource :account_link, :path => :links, :only => [:destroy]
      end
      resources :account_links, :path => :links, :only => [:index, :create]
    end

    scope :controller => :partner_accounts, :path => 'accounts' do
      resources :partner_accounts, :path => :partners, :only => [:index]
      resource :partner_account, :path => ':account_id/partner', :only => [:update]
    end

    resource :friend_rejection, :path => 'friends/:target_login/rejection', :only => [:create, :destroy]
    resource :friend_acceptance, :path => "friends/acceptance", :only => [:create, :destroy] # createでは クエリーで target_login を渡したいため
    resources :friends, :only => [:index]

    controller :deal_patterns do
      resources :deal_patterns, :path => 'deals/patterns'
      match 'deals/patterns/:id/entries', :action => 'create_entry', :as => :deal_pattern_entries, :via => [:post, :patch]
      get 'deals/patterns/codes/:code', :action => 'code', :as => :deal_pattern_codes
    end

    resource :preferences, :only => [:show, :update]

    resources :single_logins, :only => [:index, :create, :destroy]
  end

  controller :deal_patterns do
    get 'deals/patterns/recent', :action => 'recent', :as => 'recent_deal_patterns'
    resources :deal_patterns, :path => 'deals/patterns', :only => [:create]
  end

  controller :deals do
    resources :deals, :only => [:index, :edit, :update, :destroy] do
      member do
        put 'confirm'
      end
      collection do
        get 'search'
      end
    end
    get 'deals/:id/edit/deal_pattern/:pattern_code', as: :deal_pattern_in_edit, action: :load_deal_pattern_into_edit
    match 'deals/:id/entries', :action => 'create_entry', :as => :deal_entries, :via => [:post, :patch]

    ['general', 'balance', 'complex'].each do |t|
      post "#{t}_deals", :action => "create_#{t}_deal", :as => :"#{t}_deals"
      get "#{t}_deals/new", :action => "new_#{t}_deal", :as => :"new_#{t}_deal"
      post "accounts/:account_id/#{t}_deals", :action => "create_#{t}_deal", :as => :"account_#{t}_deals"
      get "accounts/:account_id/#{t}_deals/new", :action => "new_#{t}_deal", :as => :"new_account_#{t}_deal"
    end

    get 'deals/:year/:month/days', :as => :monthly_deal_days, :action => 'day_navigator'
    get 'accounts/:account_id/deals/:year/:month', as: :monthly_account_deals, action: :monthly
    get 'deals/:year/:month', :as => :monthly_deals, :action => 'monthly' #, :requirements => YEAR_MONTH_REQUIREMENTS
  end

  resources :deal_suggestions, :path => 'deals/suggestions', :only => [:index]

  get '/home' => 'home#index', :as => :home

  resource :user

  controller :settlements do
    scope path: 'accounts/:account_id' do
      get 'settlements/new/:year/:month', as: :new_account_settlement, action: :new
      put 'settlements/new/:year/:month', :action => :update_source
      post 'settlements/new/:year/:month/deals', as: :new_account_settlement_deals, :action => :select_all_deals_in_source
      delete'settlements/new/:year/:month/deals', :action => :remove_all_deals_in_source
      delete 'settlements/new/:year/:month', action: :destroy_source
      post 'settlements/:year/:month', as: :account_settlements, action: :create
      get  'settlements/:year/:month', action: :summary
    end
    resources :settlements, :only => [:show, :destroy] do
      member do
        get 'print_form'
        put 'submit'
      end
    end
    get 'settlements/:year/:month', as: :settlements, action: :summary
  end

  controller :assets do
    scope :path => 'f' do # /assets はじまりは無視されるため
      get 'assets/:year/:month', {:as => :monthly_assets, :action => :monthly}.merge(YEAR_MONTH_REQUIREMENTS)
      resources :assets, :only => [:index]
    end
  end

  controller :balance_sheet do
    get :balance_sheet, :action => :show
    get 'balance_sheet/:year/:month', {:as => :monthly_balance_sheet, :action => 'monthly'}.merge(YEAR_MONTH_REQUIREMENTS)
  end

  controller :profit_and_loss do
    get :profit_and_loss, :action => :show
    get 'profit_and_loss/:year/:month', {:as => :monthly_profit_and_loss, :action => 'monthly'}.merge(YEAR_MONTH_REQUIREMENTS)
  end

  controller :export do
    get 'export', :as => :export, :action => "index"
    get 'export/:filename.:format', :as => :export_file, :action => "whole"
  end

  controller :help do
    get 'help/index'
    get 'help/functions'
    get 'help/faq'
  end

  root :to => "welcome#index"

  get '/signup' => 'users#new', :as => :signup, :via => :get
  match '/signup' => 'users#create', :as => :signup_post, :via => :post # TODO: must be unified to signup
  match '/login' => 'sessions#create', :as => :login_post, :via => :post # TODO: change to login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/singe_login' => 'sessions#update', :as => :single_login, :via => :put
  get '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/privacy_policy' => 'users#privacy_policy', :as => :privacy_policy, :via => :get

  get '/user/home' => 'users#activate_login_engine', :as => :activate_login_engine

  get '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match  '/deliver_password_notification' => 'users#deliver_password_notification', :via => :post, :as => :deliver_password_notification
  match '/password/:password_token' => 'users#edit_password', :via => :get, :as => :password
  match '/password/:password_token' => 'users#update_password', :via => :post
end

app/models/user.rb
# ユーザーに紐づくロジックは多いので、機能別にモジュールを記述してincludeする
require 'digest/sha1'
class User < ApplicationRecord
  require 'user/friend' # TODO: User::Friendのincludeが(少なくともdevelopmentモードで)エラーになるため応急措置
  include User::Friend

  delegate :bookkeeping_style?, :to => :preferences

  has_many  :single_logins, :dependent => :destroy
  has_many  :settlements, :dependent => :destroy
  has_one   :preferences, :class_name => "Preferences", :dependent => :destroy
  has_many  :incomes, -> { order(:sort_key) },
            class_name: 'Account::Income'
  has_many  :expenses, -> { order(:sort_key) },
            class_name: 'Account::Expense'
  has_many  :assets, -> { order(:sort_key) },
            class_name: "Account::Asset" do
    def credit
      credit_asset_kinds = asset_kinds{|attributes| attributes[:credit]}.map{|k| k.to_s}
      categorized_as(*credit_asset_kinds)
    end
  end
  has_many  :flow_accounts, -> { where("asset_kind is null").order(:sort_key) },
            class_name: "Account::Base"

  has_many :deal_patterns, :class_name => "Pattern::Deal"

  ACCOUNTS_OPTIONS_ASC = ['Account::Asset', 'Account::Income', 'Account::Expense']
  ACCOUNTS_OPTIONS_DESC = ['Account::Expense', 'Account::Asset', 'Account::Income']
  has_many  :accounts, -> { order(:sort_key) }, :class_name => 'Account::Base' do

    def grouped_options(is_asc = true)
      grouped = group_by{|a| a.class}.map{|key, value| [key, value.map{|a| [a.name, a.id]}]}
      order = is_asc ? ACCOUNTS_OPTIONS_ASC : ACCOUNTS_OPTIONS_DESC
      grouped.sort!{|a, b|
        # 昇順／降順が対照的でないため独自ロジック
        order.index(a[0].name) <=> order.index(b[0].name)
      }
      grouped.map{|g| g[0] = g[0].human_name; g}
    end

    # 指定した日の最初における指定した口座の残高合計を得る
    def balance_sum(date, conditions = nil)
      where(conditions)
          .join_entries_and_deals
          .where("(deals.confirmed = ? and deals.date < ?) or account_entries.initial_balance = ?", true, date, true)
          .sum("account_entries.amount")
          .to_i
    end
    
    # 指定した日の最初における指定した口座の残高をAccountモデルの一覧として得る
    def balances(date, conditions = nil)
      where(conditions)
          .join_entries_and_deals
          .select("accounts.*, sum(account_entries.amount) as balance")
          .includes(nil)
          .where("(deals.confirmed = ? and deals.date < ?) or account_entries.initial_balance = ?", true, date, true)
          .group('accounts.id')
          .each{|a| a.balance = a.balance.to_i }
    end
    
    # 指定した期間における収入口座のフロー合計を得る。収入の不明金も含める。
    def income_sum(start_date, end_date)
      result = flow_sum(start_date, end_date, "accounts.type = 'Account::Income'")
      unknowns(start_date, end_date).delete_if{|a| a.unknown >= 0}.each{|a| result += a.unknown}
      result
    end

    # 指定した期間における支出口座のフロー合計を得る。支出の不明金も含める。
    # end_date は exclusive
    # NOTE: 不明金は正負逆転するとか、正負をそれぞれよせるかまとめてよせるかなどがあり、SQL一発でやるのは難しい
    #   例えば 擬似的に views を作り、asset 勘定ごとに任意の方向で amount がとれるようにするといいのかもしれない
    #   不明金を合体させて扱うのは総合的なところに限られるので、Accountクラスに引っ越す必要性は高くなさそう
    def expense_sum(start_date, end_date)
#      TODO: 旧 flow_sum から 新 total_flow （accounts関連から accountsクラスメソッド系へ）へ移行中。参考のため残しておく
#      result = flow_sum(start_date, end_date, "accounts.type = 'Account::Expense'")
      result = expense.total_flow(start_date, end_date-1) # inclusive に修正...
      unknowns(start_date, end_date).delete_if{|a| a.unknown <= 0}.each{|a| result += a.unknown}
      result
    end
    
    # 指定した期間における指定した口座のフロー合計を得る。不明金は扱わない。
    def flow_sum(start_date, end_date, conditions = nil)
      where(conditions)
          .join_entries_and_deals
          .where("deals.confirmed = ? and deals.date >= ? and deals.date < ? and account_entries.initial_balance != ?", true, start_date, end_date, true)
          .sum("account_entries.amount")
          .to_i
    end
    
    # 指定した期間における指定した口座のフローをAccountモデルの一覧として得る。flowカラムに格納される。
    # 資産口座の不明金を結果に足すことはしない。
    # 記入のない口座は取得されない。
    def flows(start_date, end_date, conditions = nil)
      where(conditions)
          .join_entries_and_deals
          .select("accounts.*, sum(account_entries.amount) as flow")
          .includes(nil)
          .where("deals.confirmed = ? and deals.date >= ? and deals.date < ? and account_entries.initial_balance != ?", true, start_date, end_date, true)
          .group('accounts.id')
          .to_a.each{|a| a.flow = a.flow.to_i}
    end

    # 指定した期間における指定した口座の不明金を Accountモデルの一覧として得る。不明金は unknown カラムに格納される。
    # 不明金勘定の視点から、正負は逆にする。つまり、支出の不明金はプラスで出る。
    def unknowns(start_date, end_date, conditions = nil)
      where(conditions)
          .join_entries_and_deals
          .select("accounts.*, sum(account_entries.amount) as unknown")
          .includes(nil)
          .where("deals.type = 'Deal::Balance' and deals.confirmed = ? and deals.date >= ? and deals.date < ? and account_entries.initial_balance != ?", true, start_date, end_date, true)
          .group('accounts.id')
          .to_a.each{|a| a.unknown = a.unknown.to_i; a.unknown *= -1 }
        # Rails5.0にあげたとき、to_a をはさまずに each すると結果が frozen になってしまった
    end
  
    # 指定した account_type のものだけを抽出する
    # TODO: 遅いので修正する
#    def types_in(*account_types)
#      account_types = account_types.flatten
#      self.select{|a| account_types.detect{|t| a.type_in?(t)} }
#    end
    
  end

  after_create :create_defaults

#  # TODO: 関連に移行
#  def assets
#    accounts.types_in(:asset)
#  end

  # ProxyUser共通で使えるAccountオブジェクトを取得。この時点ではまだ通信は発生しない
  def account(account_id)
     accounts.find(account_id)

#    AccountProxy.new(account_id)
  end

  # ProxyUser共通で使えるAccountオブジェクトを取得。この時点ではまだ通信は発生しない
  def account_by_name(account_name)
    accounts.find_by(name: account_name)

#    AccountProxy.new(account_id)
  end

  include User::AccountLinking
  
  has_many :deals, :class_name => 'Deal::Base', :extend => User::DealsExtension
  # 作成用
  has_many :general_deals, :class_name => "Deal::General", :foreign_key => "user_id"
  has_many :balance_deals, :class_name => "Deal::Balance", :foreign_key => "user_id"

  has_many :entries,         class_name: "Entry::Base"
  has_many :general_entries, class_name: "Entry::General"
  
  def default_asset
    assets.first
  end

  # TODO: 賢くしたい
  def default_asset_other_than(*excludes)
    assets.detect{|a| !excludes.include?(a)}
  end

  # all logic has been moved into login_engine/lib/login_engine/authenticated_user.rb
  def login_id
    self.login
  end
  
  # TODO: メソッド不要
  def self.find_by_login_id(login_id)
    find_by(login: login_id)
  end
  
  def deal_exists?(date)
    Deal::Base.exists?(self.id, date)
  end
  

  def available_asset_kinds
    if preferences.business_use? && defined?(EXTENSION_ASSET_KINDS) && EXTENSION_ASSET_KINDS[:business]
      Account::Asset::BASIC_KINDS.merge(EXTENSION_ASSET_KINDS[:business])
    else
      Account::Asset::BASIC_KINDS
    end
  end

  
  # Virtual attribute for the unencrypted password
  attr_accessor :password

  validates :login, presence: true, length: {within: 3..40,  allow_blank: true}, uniqueness: {case_sensitive: false, allow_blank: true}
  validates :email, presence: true, length: {within: 3..100, allow_blank: true}, uniqueness: {case_sensitive: false, allow_blank: true}

  with_options if: :password_required? do |req|
    req.validates :password,              presence: true, length: {within: 4..40,  allow_blank: true}, confirmation: true
    req.validates :password_confirmation, presence: true
  end

  before_save :encrypt_password
  before_create :make_activation_code
  after_destroy :destroy_deals, :destroy_accounts

  # Activates the user in the database.
  def activate
    @activated = true
    self.activated_at = Time.zone.now.utc
    self.activation_code = nil
    save(:validate => false)
  end

  def active?
    # the existence of an activation code means they have not activated yet
    activation_code.nil?
  end

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = where('login = ? and activated_at IS NOT NULL', login).first # need to get the salt
    u && u.authenticated?(password) ? u.upgrade!(password) : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.zone.now.utc < remember_token_expires_at
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token            = encrypt("#{email}--#{remember_token_expires_at}")
    save(:validate => false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(:validate => false)
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  def update_password_token
    self.password_token_expires_at = 3.days.from_now.utc
    self.password_token            = encrypt("p-#{email}--#{password_token_expires_at}")
    save(:validate => false)
  end

  def password_token?
    password_token_expires_at && Time.zone.now.utc < password_token_expires_at
  end
  
  def change_password(password, password_confirmation)
    self.password = password
    self.password_confirmation = password_confirmation
    result = false
    User.transaction do
      result = save
      # パスワードが変更できたら、activateして、クラスを強制的に変える
      if result
        self.password_token = nil
        self.password_token_expires_at = nil
        unless self.active?
          @activated = true

app/views/settlements/_month_navigator.html.haml
%table
  - displayed_years = []
  - @months.each do |monthly_date, entries|
    - unless displayed_years.include?(monthly_date.year)
      %tr.year
        %td.year{colspan: 2}= "#{monthly_date.year}年"
      - displayed_years << monthly_date.year
    %tr.month{class: monthly_date.year == Time.zone.today.year && monthly_date.month == Time.zone.today.month ? 'now' : nil, data: {first_date: entries.first.try(:date), last_date: entries.last.try(:date), year: monthly_date.year, month: monthly_date.month}}
      %td.month= "#{monthly_date.month}月"
      %td= entries.present? ? "*" : ''

app/views/settlements/_settlement.html.haml
%tr
  - unless settlement.result_entry
    %td{colspan: 5}= "請求(ID:#{settlement.id}、「#{s.name}」、相手先：#{settlement.account ? settlement.account.name : '？'})のデータが破損しています。精算取引がありません。管理者に連絡してください。"
  - else
    %td.date= format_date settlement.result_entry.deal.date
    %td= settlement.name
    %td{style: "text-align:right;"}= settlement.target_entries.size
    %td.amount= link_to number_with_delimiter(settlement.amount), settlement_path(settlement)
    %td= format_datetime settlement.created_at
  %td
    - if settlement.submitted_settlement_id
      提出済
    - elsif settlement.kind_of?(SubmittedSettlement)
      受理

app/views/settlements/_summary.html.haml
- gadget ||= false
%table.book.settlements_summary
  - unless gadget
    %tr
      %th
      - @settlement_summaries.years.each do |year, months|
        %th{colspan: months.size}= "#{year}年"
  %tr
    - unless gadget
      %th
        .pull-right
          - if @settlement_summaries.previous_target_date
            = link_to '前へ', {year: @settlement_summaries.previous_target_date.year, month: @settlement_summaries.previous_target_date.month}, class: %w(btn btn-info btn-sm)
    - @settlement_summaries.months.each do |monthly_date|
      %th
        - caption = "#{monthly_date.month}月"
        - caption << "の精算" if gadget
        = caption
    - unless gadget
      - if @settlement_summaries.next_target_date
        %th
          .pull-left
            = link_to '後へ', {year: @settlement_summaries.next_target_date.year, month: @settlement_summaries.next_target_date.month}, class: %w(btn btn-info btn-sm)
  - @settlement_summaries.each do |account, account_settlements_per_months|
    %tr
      - unless gadget
        %th
          = link_to_if !@settlement_summaries.target_account, "#{account.name}の精算", account_settlements_path(account_id: account.id)
      - account_settlements_per_months.each do |monthly_date, (settlements, unsettled_entries_amount)|
        %td.settlement{class: monthly_date.year == current_year.to_i && monthly_date.month == current_month.to_i ? "target_month" : nil}
          - shown = false
          - if settlements.present?
            - settlements.each do |s|
              %div= link_to number_with_delimiter(s.amount), settlement_path(s.id)
            - shown = true
          - if unsettled_entries_amount
            = number_with_delimiter(unsettled_entries_amount)
            %br
            = link_to '作成', new_account_settlement_path(account_id: account.id, year: monthly_date.year, month: monthly_date.month), class: %w(btn btn-sm) + [settlement_source_exists?(account, monthly_date.year, monthly_date.month) ? 'btn-warning' : 'btn-default']
            - shown = true
          - unless shown
            &nbsp;
      - unless gadget
        - if @settlement_summaries.next_target_date
          %th{width: "20px;"}

app/views/settlements/account_settlements.html.haml
#settlements_right
  = link_to "概況", settlements_path(year: current_year, month: current_month), class:  %w(btn btn-default)
  %hr
  = link_to @account.name, monthly_account_deals_path(account_id: @account.id, year: Time.zone.today.year, month: Time.zone.today.month), class: %w(btn btn-default)

#settlements_main
  #settlements
    - if flash[:notice]
      %div= flash[:notice]
    .row
      .col-xs-4
        = form_tag '' do
          #account_options
            = select_tag :account_id, options_for_select(current_user.assets.credit.map{|a| [a.name_with_asset_type, a.id]}, @account.try(:id).to_s), class: %w(switcher form-control), data: {url_template: account_settlements_path(account_id: "_SWITCHER_VALUE_")}
      .col-xs-8

    %h3 一覧
    - if @settlements.empty?
      %p 精算データはありません。
    - else
      %table.book
        %tr
          %th.date 精算日
          %th 精算データ名
          %th 対象取引数
          %th.amount 精算額
          %th 登録日時
          %th 状態
        = render :partial => 'settlement', :collection => @settlements

app/views/settlements/new.html.haml
:javascript
  var settlement = new Settlement;

#settlements_left
  #month_navigator_frame
    = render partial: 'month_navigator'

#settlements_right
  = account_button(@source.account, @source.start_date.year, @source.start_date.month)
  = link_to "#{@source.account.name}の精算", account_settlements_path(account_id: @source.account.id), class:  %w(btn btn-default monthly_deals_link), data: {url_template: monthly_deals_path(year: '_YEAR_', month: '_MONTH_')}

  #recent_settlements
    %h3 最近の精算
    %ul
      - @source.account.result_settlements.recent(6).each do |s|
        %li= link_to "#{s.name} - #{s.result_entry.date}", settlement_path(s)

#settlements_main
  = form_for :source, url: account_settlements_path, html: {id: 'target_deals_form', data: {url: url_for(:action => 'update_source', :clear_selection => true)}} do |f|
    #select_credit_account
      .row
        .col-xs-4
          = select_tag :account_id, options_for_select(current_user.assets.credit.map{|a| [a.name, a.id]}, @source.account.id), class: 'form-control account_selector', data: {url_template: new_account_settlement_path(account_id: "_ACCOUNT_ID_")}
        .col-xs-1
          .row
            .col-xs-3
              - if @source.account.description.present?
                = render partial: 'shared/account_memo', locals: {account: @source.account}
            .col-xs-3
              %a{href: setting_account_path(@source.account)}
                %span.glyphicon.glyphicon-wrench
        .col-xs-5{style: "margin-top: 8px;"}
          = select_date(@source.start_date, prefix: 'source[start_date]', use_month_numbers: true, start_year: current_user.pragmatic_start_year, end_year: Time.zone.now.year+1)
          ～
          = select_date(@source.end_date, prefix: 'source[end_date]', use_month_numbers: true, start_year: current_user.pragmatic_start_year, end_year: Time.zone.now.year+1)
        .col-xs-1
          = link_to '初期化する', {action: :destroy_source}, method: :delete, class: 'btn-danger btn', type: 'button', data: {confirm: "作成途中の内容を破棄して内容を初期化します。よろしいですか？"}

    - if @settlement&.errors&.present?
      %div= error_messages_for 'settlement'
    #target_deals
      = render partial: 'target_deals'

app/views/settlements/no_settlement.html.haml
%p 精算データはありません。

app/views/settlements/show.html.haml
#settlements_right
  - if @settlement.deletable?
    = link_to '精算の削除', settlement_path(:id => @settlement.id), :method => :delete, :data => {:confirm => "精算データを削除すると、精算結果の取引も自動的に削除されます。精算データを削除してよろしいですか？"}, class: %w(btn btn-danger)
  - unless @settlement.kind_of?(SubmittedSettlement)
    = link_to '精算依頼書', print_form_settlement_path(:id => @settlement), 'data-popup' => true, class: %w(btn btn-default)
    - if @settlement.result_entry
      - if @settlement.submitted_settlement_id.blank? && @settlement.account.destination_account
        = button_to "提出する", submit_settlement_path(:id => @settlement), :method => :put, :class => 'button', :data => {:confirm => "この精算内容を#{@settlement.account.destination_account.user_login}さんに提出済の状態にします。以後、#{@settlement.account.destination_account.user_login}さんがこの精算の提出を取り消すまで、こちらからは変更、削除、提出の取消が行えなくなります。提出済にしてよろしいですか？"}, class: %w(btn btn-warning)
  - if @settlement.deletable? || !@settlement.kind_of?(SubmittedSettlement)
    %hr
  = account_button(@settlement.account, @settlement.result_entry.date.year, @settlement.result_entry.date.month)
  %hr
  = link_to "#{@settlement.account.name}の精算", account_settlements_path(account_id: @settlement.account.id, year: @settlement.result_entry.date.year, month: @settlement.result_entry.date.month), class: %w(btn btn-default)
  = link_to 'すべての精算', settlements_path(year: current_year, month: current_month), class: %w(btn btn-default)

#settlements_main
  %h3 精算の基本情報
  .panel.panel-default
    %table.table
      %tr
        %th 精算データ名
        %td= @settlement.name
      %tr
        %th 精算対象口座
        %td= @settlement.account.name
      %tr
        %th 精算日
        %td= format_date @settlement.result_entry.date
      %tr
        %th 精算金額
        %td= number_with_delimiter(@settlement.amount)
      %tr
        %th 登録日時
        %td= format_datetime @settlement.created_at
  - if @settlement.kind_of?(SubmittedSettlement)
    %p= "この精算は#{@settlement.resource.user.login}さんから提出されたことによりできたものです。"
    - # 確定状態
    %p
      - if @settlement.all_confirmed?
        この精算は確認済です。
      - else
        この精算には未確認の取引が含まれています。
  - if @settlement.submitted_settlement
    %p= "この精算は#{@settlement.submitted_settlement.user.login}さんに提出済です。削除するには先方に取消を依頼してください。"

  %h3 精算対象
  %table.book
    %tr
      = display_account_entry_header
      %th.icon_to_deal
    - for target_entry in @settlement.target_entries
      %tr
        = display_account_entry(target_entry)
        %td.icon_to_deal= icon_to_deal_in_monthly(target_entry.year, target_entry.month, target_entry.deal_id)

  %h3 精算結果
  - unless @settlement.result_entry
    %div{style: "color:red; font-weight: bold;"} データが破損しています。精算取引がありません。管理者に連絡してください。
  - else
    %table.book
      %tr
        = display_account_entry_header
        %th.icon_to_deal
      %tr
        = display_account_entry(@settlement.result_entry)
        %td.icon_to_deal= icon_to_deal_in_monthly(@settlement.result_entry.year, @settlement.result_entry.month, @settlement.result_entry.deal_id)

app/views/settlements/summary.html.haml
#deals_left
  = render partial: 'summary'
#deals_right
  - if @account
    = account_button(@account, current_year, current_month)
    %hr
    = link_to 'すべての精算', settlements_path(year: current_year, month: current_month), class: %w(btn btn-default)
  - else
    = link_to '総合', monthly_deals_path(year: current_year, month: current_month), class: %w(btn btn-default monthly_deals_link), data: {url_template: monthly_deals_path(year: '_YEAR_', month: '_MONTH_')}
    - account_selection_histories.each do |a|
      = account_button(a, current_year, current_month)