config/routes.rb
YEAR_MONTH_REQUIREMENTS = {:year => /[0-9]*|_YEAR_/, :month => /[1-9]|10|11|12|_MONTH_/}

Rails.application.routes.draw do

  namespace :settings do
    controller :accounts do
      %w(asset income expense).each do |type|
        with_options account_type: type do |with_type|
          with_type.put type.pluralize, :action => :update_all
          with_type.resources type.pluralize, controller: :accounts, only: [:index, :show, :create, :update, :destroy]
        end
      end
    end

    resources :account_link_requests, :path => 'accounts/:account_id/link_requests', :only => [:destroy]

    scope :controller => :account_links, :path => 'accounts' do
      scope :path => ':account_id' do
        resource :account_link, :path => :links, :only => [:destroy]
      end
      resources :account_links, :path => :links, :only => [:index, :create]
    end

    scope :controller => :partner_accounts, :path => 'accounts' do
      resources :partner_accounts, :path => :partners, :only => [:index]
      resource :partner_account, :path => ':account_id/partner', :only => [:update]
    end

    resource :friend_rejection, :path => 'friends/:target_login/rejection', :only => [:create, :destroy]
    resource :friend_acceptance, :path => "friends/acceptance", :only => [:create, :destroy] # createでは クエリーで target_login を渡したいため
    resources :friends, :only => [:index]

    controller :deal_patterns do
      resources :deal_patterns, :path => 'deals/patterns'
      match 'deals/patterns/:id/entries', :action => 'create_entry', :as => :deal_pattern_entries, :via => [:post, :patch]
      get 'deals/patterns/codes/:code', :action => 'code', :as => :deal_pattern_codes
    end

    resource :preferences, :only => [:show, :update]

    resources :single_logins, :only => [:index, :create, :destroy]
  end

  controller :deal_patterns do
    get 'deals/patterns/recent', :action => 'recent', :as => 'recent_deal_patterns'
    resources :deal_patterns, :path => 'deals/patterns', :only => [:create]
  end

  controller :deals do
    resources :deals, :only => [:index, :edit, :update, :destroy] do
      member do
        put 'confirm'
      end
      collection do
        get 'search'
      end
    end
    get 'deals/:id/edit/deal_pattern/:pattern_code', as: :deal_pattern_in_edit, action: :load_deal_pattern_into_edit
    match 'deals/:id/entries', :action => 'create_entry', :as => :deal_entries, :via => [:post, :patch]

    ['general', 'balance', 'complex'].each do |t|
      post "#{t}_deals", :action => "create_#{t}_deal", :as => :"#{t}_deals"
      get "#{t}_deals/new", :action => "new_#{t}_deal", :as => :"new_#{t}_deal"
      post "accounts/:account_id/#{t}_deals", :action => "create_#{t}_deal", :as => :"account_#{t}_deals"
      get "accounts/:account_id/#{t}_deals/new", :action => "new_#{t}_deal", :as => :"new_account_#{t}_deal"
    end

    get 'deals/:year/:month/days', :as => :monthly_deal_days, :action => 'day_navigator'
    get 'accounts/:account_id/deals/:year/:month', as: :monthly_account_deals, action: :monthly
    get 'deals/:year/:month', :as => :monthly_deals, :action => 'monthly' #, :requirements => YEAR_MONTH_REQUIREMENTS
  end

  resources :deal_suggestions, :path => 'deals/suggestions', :only => [:index]

  get '/home' => 'home#index', :as => :home

  resource :user

  controller :settlements do
    scope path: 'accounts/:account_id' do
      get 'settlements/new/:year/:month', as: :new_account_settlement, action: :new
      put 'settlements/new/:year/:month', :action => :update_source
      post 'settlements/new/:year/:month/deals', as: :new_account_settlement_deals, :action => :select_all_deals_in_source
      delete'settlements/new/:year/:month/deals', :action => :remove_all_deals_in_source
      delete 'settlements/new/:year/:month', action: :destroy_source
      post 'settlements/:year/:month', as: :account_settlements, action: :create
      get  'settlements/:year/:month', action: :summary
    end
    resources :settlements, :only => [:show, :destroy] do
      member do
        get 'print_form'
        put 'submit'
      end
    end
    get 'settlements/:year/:month', as: :settlements, action: :summary
  end

  controller :assets do
    scope :path => 'f' do # /assets はじまりは無視されるため
      get 'assets/:year/:month', {:as => :monthly_assets, :action => :monthly}.merge(YEAR_MONTH_REQUIREMENTS)
      resources :assets, :only => [:index]
    end
  end

  controller :balance_sheet do
    get :balance_sheet, :action => :show
    get 'balance_sheet/:year/:month', {:as => :monthly_balance_sheet, :action => 'monthly'}.merge(YEAR_MONTH_REQUIREMENTS)
  end

  controller :profit_and_loss do
    get :profit_and_loss, :action => :show
    get 'profit_and_loss/:year/:month', {:as => :monthly_profit_and_loss, :action => 'monthly'}.merge(YEAR_MONTH_REQUIREMENTS)
  end

  controller :export do
    get 'export', :as => :export, :action => "index"
    get 'export/:filename.:format', :as => :export_file, :action => "whole"
  end

  controller :help do
    get 'help/index'
    get 'help/functions'
    get 'help/faq'
  end

  root :to => "welcome#index"

  get '/signup' => 'users#new', :as => :signup, :via => :get
  match '/signup' => 'users#create', :as => :signup_post, :via => :post # TODO: must be unified to signup
  match '/login' => 'sessions#create', :as => :login_post, :via => :post # TODO: change to login
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/singe_login' => 'sessions#update', :as => :single_login, :via => :put
  get '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/privacy_policy' => 'users#privacy_policy', :as => :privacy_policy, :via => :get

  get '/user/home' => 'users#activate_login_engine', :as => :activate_login_engine

  get '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match  '/deliver_password_notification' => 'users#deliver_password_notification', :via => :post, :as => :deliver_password_notification
  match '/password/:password_token' => 'users#edit_password', :via => :get, :as => :password
  match '/password/:password_token' => 'users#update_password', :via => :post
end

app/models/deal/balance.rb
# 残高確認記入行クラス

# * 登録時は、account_id, balanceをセットしてsaveする。
# * 参照時は、account_id, balanceで既存のAccountEntryのデータにアクセスできる。
class Deal::Balance < Deal::Base

  before_validation :set_user_id_to_entry
  before_create :set_date_and_daily_seq_to_entry
  before_update :rebuild_entry
  before_destroy :cache_account_id # entry より上にないといけない（entryが削除される前に実行する必要がある）
  
  has_one   :entry, :class_name => "Entry::Balance",
             :foreign_key => 'deal_id',
             :dependent => :destroy,
             :autosave => true

  after_save :update_initial_balance
  after_destroy :update_initial_balance

  delegate :account_id=, :account_id, :account, :balance=, :balance, :balance_before_type_cast, :amount, :summary, :initial_balance?, :balance_before, :summary_truncated?, to: :prepared_entry

  def balance?
    true
  end

  def build_entry
    super
    # あれば入れる。登録前にも入れる
    entry.user_id = user_id
    entry.date = date
    entry.daily_seq = daily_seq
    entry.confirmed = confirmed
    entry
  end

  def summary_unified?
    true
  end

  def to_xml(options = {})
    options[:indent] ||= 4
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])
    xml.instruct! unless options[:skip_instruct]
    xml.balance(:id => "balance#{self.id}", :date => self.date_as_str, :position => self.daily_seq, :account => "account#{self.account_id}") do
      xml.description XMLUtil.escape(self.summary)
      xml.amount self.readonly_entries.first.try(:balance)
    end
  end

  def to_csv
    ["balance", self.id, date_as_str, daily_seq, account_id, balance].join(",")
  end

  # amount（最初の残高以外は不明金として扱われる）を再計算して更新
  # 自分が「最初の残高」なら、最初の残高を考慮しない残高計算をする
  # AccountEntryのupdate_balanceから呼ばれる
  # これを順々にやれば残高不正は修正できると思われる
  def update_amount
    amount = entry.balance.to_i - balance_before(entry.initial_balance?)
    Entry::Base.where(id: entry.id).update_all("amount = #{amount}")
    entry.amount = amount
  end

  private

  def prepared_entry
    build_entry unless entry
    entry
  end

  # 更新時は、entryが変更されていたら必ず一度削除して作り直す
  def rebuild_entry
    return unless entry.changed?
    entry_attributes = entry.attributes.slice('account_id', 'balance')
    entry.destroy
    build_entry
    entry.attributes = entry_attributes
  end

  # 検証で利用するため user_id は先に必要となる
  def set_user_id_to_entry
    raise "no user_id" unless user_id
    entry.user_id = user_id
  end

  def set_date_and_daily_seq_to_entry
    raise "no date" unless date
    entry.date = date
    raise "no daily_seq" unless daily_seq
    entry.daily_seq = daily_seq
    entry.confirmed = confirmed
  end

  def cache_account_id
    account_id # entries を検索して account_id をキャッシュする
  end

  # 対象口座のinitial_balance値を更新する
  def update_initial_balance
    raise "no account_id" unless account_id
    initial_balance_entry = Entry::Balance.of(account_id).ordered.first
    # 現在ひとつもないなら特に仕事なし
    return unless initial_balance_entry # destroyの際はこれが起きる可能性がある
    # すでにマークがついていたら仕事なし
    return if initial_balance_entry.initial_balance?

    # マークがついていない＝状態が変わったので修正する
    Entry::Base.where(account_id: account_id).update_all(["initial_balance = ?", false])
    Entry::Base.where(id: initial_balance_entry.id).update_all(["initial_balance = ?", true])
    # オブジェクトがあるときはオブジェクトの状態も変えておく
    entry.initial_balance = true if entry && entry.id == initial_balance_entry.id
  end

end

app/controllers/concerns/deals/summary_truncation.rb
module Deals::SummaryTruncation
  extend ActiveSupport::Concern

  private

  def truncation_message(deal)
    deal.summary_truncated? ? "長すぎる摘要を64文字に短縮しました。" : ""
  end
end

app/helpers/deals_helper.rb
module DealsHelper

  def account_button(account, year, month)
    # link_to truncate(account.name, length: 10), monthly_account_deals_path(account_id: account.id, year: year, month: month), class:  %w(btn btn-default monthly_deals_link), data: {url_template: monthly_deals_path(year: '_YEAR_', month: '_MONTH_')}
  end

  def money_count_field(name, caption)
    content_tag :div, class: %w(field) do
      html = label_tag name, caption
      html << text_field_tag(name, size: 2, autocomplete: 'off')
      html << content_tag(:span, '枚')
    end
  end

  # 仕訳帳中の指定された deal を示すURLを生成する
  # 以下のいずれかの引数をとる
  # * dealオブジェクトのみ
  # * entryオブジェクトのみ
  # * year, month, deal_id の３つ
  def icon_to_deal_in_monthly(*args)
    year, month, deal_id = case args.first
    when Deal::Base
      [args.first.year, args.first.month, args.first.id]
    when Entry::Base
      [args.first.year, args.first.month, args.first.deal_id]
    else
      raise "3 parameters required" unless args.size == 3
      args
    end
    link_to '→', monthly_deals_path(:year => year, :month => month, :anchor => 'd' + deal_id.to_s)
  end

  def write_hiddens_and_get_simple_deal_procs(f, options = {})
    amount_field_proc = nil
    debtor_account_field_proc = nil
    creditor_account_field_proc = nil
    f.fields_for :debtor_entries do |e|
      fixed_account = options[:debtor_account_fixed]
      fixed_account ||=  e.object.account if e.object.settlement_attached?
      
      if e.object.marked_for_destruction?
        concat(e.hidden_field :_delete, :value => '1')
      else
        amount_unchangable = e.object.settlement_attached?
        amount_field_proc = lambda{|tabindex | (e.text_field(:amount, {:size => "8", :disabled => amount_unchangable, :class => "amount#{amount_unchangable ? '' : ' pattern_field'}", :tabindex => tabindex}.merge(amount_unchangable ? {:id => nil} : {}))) + (amount_unchangable ? e.hidden_field(:amount, :class => 'pattern_field') : '')}
        debtor_account_field_proc = if fixed_account
          lambda{|tabindex|
            ("<input type='text' disabled='true' class='readonly' value='#{fixed_account.name}' tabindex='#{tabindex}' />" +
            e.hidden_field(:account_id, :value => fixed_account.id, :class => 'pattern_field')).html_safe
          }
        else
          lambda{|tabindex| (e.select :account_id, grouped_options_for_select(@user.accounts.active.grouped_options(false), e.object.account_id), {}, :tabindex => tabindex, :class => 'pattern_field').html_safe }
        end
      end
    end

    f.fields_for :creditor_entries do |e|
      fixed_account = options[:creditor_account_fixed]
      fixed_account ||=  e.object.account if e.object.settlement_attached?

      if e.object.marked_for_destruction?
        concat(e.hidden_field :_delete, :value => '1')
      else
        creditor_account_field_proc = if fixed_account
          lambda{|tabindex|
            ("<input type='text' disabled='true' class='readonly' value='#{fixed_account.name}' tabindex='#{tabindex}' />" +
            e.hidden_field(:account_id, :value => fixed_account.id, :class => 'pattern_field')).html_safe
          }
        else
          lambda{|tabindex| (e.select :account_id, grouped_options_for_select(@user.accounts.active.grouped_options(true), e.object.account_id), {}, :tabindex => tabindex, :class => 'pattern_field').html_safe }
        end
      end
    end

    return amount_field_proc, debtor_account_field_proc, creditor_account_field_proc
  end


  def deal_editor(start_tab_index = 1, year = nil, month = nil, day = nil, &block)
    tab_index = start_tab_index
    text = content_tag(:div, class: 'datebox') do
      content_tag :form, class: 'datebox_form' do
        d = ''
        d << text_field(:date, :year, :size => 4, :max_length => 4, :tabindex => tab_index, :value => year)
        tab_index += 1
        d << text_field(:date, :month, :size => 2, :max_length => 2, :tabindex => tab_index, :value => month)
        tab_index += 1
        d << text_field(:date, :day, :size => 2, :max_length => 2, :tabindex => tab_index, :value => day)
        d << ' '
        d << content_tag(:a, '月末', :class => 'end_of_month_button')
        d.html_safe
      end
    end
    text << content_tag(:div, capture(&block), :id => "deal_forms")
    text.html_safe
  end

  # 記入モード切り替えのタブ(div)を出力する
  # link_html_options に :class が渡されることは想定していない
  def deal_tab(caption, url, current_caption, link_html_options = {})
    selected = current_caption == true || current_caption == caption
    link_to caption, url, {class: %w(btn btn-default pull-right) + (selected ? %w(active) : []) }.merge(link_html_options)
  end

  def deal_form(current_caption, options = {}, &block)
    text = "<div id='tabwindow'>"
    text << render(:partial => 'deal_tabs', :locals => {:deal => @deal, :current_caption => current_caption})
    text << "<div id='tabsheet' class='tabsheet'>"
    html_options = options.delete(:html) || {}
    text << form_for(@deal, :as => :deal, :url => options[:url], :html => {:id => 'deal_form'}.merge(html_options)) do |f|
      h = f.hidden_field(:year)
      h << f.hidden_field(:month)
      h << f.hidden_field(:day)
      h << capture(f, &block)
#      yield f
      h.html_safe
    end
    text << "</div>"
    text << "</div>"
    text.html_safe
  end

  def datebox
    content_tag :div, class: "datebox" do
      content_tag :form, class: "datebox_form" do
        text_field(:date, :year, :size => 4, :max_length => 4, :tabindex => 1) +
          text_field(:date, :month, :size => 2, :max_length => 2, :tabindex => 2) +
          text_field(:date, :day, :size => 2, :max_length => 2, :tabindex => 3)
      end
    end
  end

end

app/views/deals/_account_entries.html.haml
#monthly_contents
  %table.book.book_header
    %tr
      %th.date 日付
      %th.number
      %th 摘要
      %th.account
      %th.amount= debtor_term(@account)
      %th.amount= creditor_term(@account)
      %th.settlement
      %th.amount
        - if bookkeeping_style? || @account.kind_of?(Account::Asset)
          残高
        - else
          合計
      %th.icon_to_deal
      %th.action 詳細
    - if @account.kind_of?(Account::Asset)
      %tr
        %td.date
        %td.number
        %td 期首残高
        %td
        %td
        %td
        %td.settlement
        %td.amount= number_with_delimiter(@account_entries.balance_start)
        %td.icon_to_deal
        %td
    - date = Date.new(@year.to_i, @month.to_i, 1)
    - balance_start = @account.kind_of?(Account::Asset) ? @account_entries.balance_start : 0
    - sign = @account.kind_of?(Account::Income) ? -1 : 1
    - @account_entries.each do |deal, entries|
      - entries.each do |entry|
        - tr_class = ["d#{deal.id}"].tap{|a| a << 'balance_line' if entry.balance?; a << 'unconfirmed' unless deal.confirmed?; a << "last_entry" if entry == entries.last }
        = content_tag :tr, class: tr_class, id: entry == entries.first ? "d#{deal.id}" : nil do
          - if entry == entries.first
            %td.date{rowspan: entries.size}
              - while date <= entry.date
                = day_anchor date
                - date += 1
              = l entry.date
              - if @account_entries.entries.last == entry
                - while date.month == entry.date.month
                  = day_anchor date
                  - date += 1
              - unless deal.confirmed?
                %br
                %span.system 未確定
            %td.number{id: "e#{entry.id}", rowspan: entries.size}
              = render 'shared/deal_note', :deal => deal
              %span{id: deal.id}= deal.daily_seq
          %td= entry.summary
          %td.account= entry.partner_account_name
          %td.amount= number_with_delimiter(entry.amount) if entry.amount >= 0 && !entry.initial_balance?
          %td.amount= number_with_delimiter(entry.reversed_amount) if entry.amount < 0 && !entry.initial_balance?
          %td.settlement.jump
            - if entry.any_settlement_id
              %div= link_to '精算', settlement_path(:id => entry.any_settlement_id)
          %td.amount= deal.confirmed ? number_with_delimiter(balance_start + (entry.pure_balance * sign)) : '*'
          %td.icon_to_deal= icon_to_deal_in_monthly entry.date.year, entry.date.month, deal.id
          - if entry == entries.first
            %td.action.open_detail{data: {url: deal_path(id: deal.id)}, rowspan: entries.size}
              %span{style: "font-size: small;"} 詳細
      %tr{class: [:detail_row, "d#{deal.id}"], style: "display: none;"}
        %td{colspan: "10"}
          = render partial: 'detail', locals: {deal: deal}
    - if @account.kind_of?(Account::Asset)
      %tr
        %td.date
        %td.number
        %td 期末残高
        %td
        %td
        %td
        %td.settlement
        %td.amount= number_with_delimiter(@account_entries.balance_end)
        %td.icon_to_deal
        %td
    - else
      %tr
        %td.date
        %td.number
        %td 期末合計
        %td
        %td
        %td
        %td.settlement
        %td.amount= number_with_delimiter(@account_entries.pure_balance_end)
        %td.icon_to_deal
        %td

app/views/deals/_balance_deal_form.html.erb
<%= deal_form '残高',
              :url => {action: :create_balance_deal} do |f| %>
  <%= render :partial => 'balance_deal_form_contents', :locals => {:f => f} %>
<% end %>
<%= error_messages_for :deal %>

app/views/deals/_deals.html.haml
- # TODO: @deals 以外を利用したいケースができたので、locals で deals があればそれを優先する
- # skip_deal_id が指定されていたら #dXXX の id を振らない（詳細画面など）
- skip_deal_id ||= false
- deals ||= @deals
%table.book.book_header
  %tr
    %th.date 日付
    %th.number
    %th 摘要
    %th.account{colspan: "2"}
    %th.jump
    %th.amount= term :debtor
    %th.amount= term :creditor
    %th.amount 残高
    %th.action 変更
    %th.action 削除
  - for deal in deals
    - for account_entry in deal.readonly_entries
      - tr_classes = [].tap{|a| a << "d#{deal.id}" unless skip_deal_id; a << 'unconfirmed' unless deal.confirmed?; a << "last_entry" if account_entry == deal.readonly_entries.last}
      = content_tag :tr, class: tr_classes.empty? ? nil : tr_classes, id: (account_entry == deal.readonly_entries.first && !skip_deal_id) ? "d#{deal.id}" : nil do
        - size = deal.readonly_entries.size
        - if deal.readonly_entries.first == account_entry

          - # date
          = content_tag :td, :class => 'date', :rowspan => size do
            - deal.anchor_dates.each do |date|
              = day_anchor date
            = l deal.date
            - if !deal.confirmed?
              = link_to '確認', confirm_deal_path(:id => deal), :class => 'small_button deal_confirmation_link', :alt => '確認状態にします。'

          - # number
          = content_tag :td, :class => 'number', :rowspan => size do
            = render :partial => 'shared/deal_note', :locals => {:deal => deal}
            = content_tag(:span, deal.daily_seq, id: deal.id, class: :deal_id)

        - # summary
        = content_tag :td, deal.summary_unified? ? deal.summary : account_entry.summary, :class => 'summary', :rowspan => deal.summary_unified? ? size : 1 if !deal.summary_unified? || deal.readonly_entries.first == account_entry

        - # account
        - if account_entry.linked_ex_entry_id || account_entry.kind_of?(Entry::General) && (account_entry.settlement_id || account_entry.result_settlement_id)
          %td
            = display_account_name(account_entry.account)
          %td.jump
            - if account_entry.linked_ex_entry_id
              %span{class: account_entry.linked_ex_entry_confirmed? ? nil : 'unconfirmed'} 連携
            - if account_entry.any_settlement_id
              %div
                = link_to '精算', settlement_path(:id => account_entry.any_settlement_id)
        - else
          %td.account{colspan: "2"}= account_entry.account.name

        %td.account_deals_link= link_to '→', monthly_account_deals_path(:account_id => account_entry.account.id, :year => @year, :month => @month, :anchor => "d#{deal.id}")
        %td.amount= number_with_delimiter(account_entry.amount) if account_entry.amount  > 0 && !account_entry.initial_balance?
        %td.amount= number_with_delimiter(account_entry.amount.abs) if account_entry.amount < 0 && !account_entry.initial_balance?
        %td.amount= number_with_delimiter(account_entry.balance)
        - if deal.readonly_entries.first == account_entry
          %td.action{rowspan: deal.readonly_entries.size}= link_to '変更', {:action => 'edit', :id => deal.id}, class: 'edit_deal', data: {deal_id: deal.id}
          %td.action{rowspan: deal.readonly_entries.size}
            - unless deal.settlement_attached?
              = link_to '削除', deal_path(:id => deal), :data => {:confirm => "#{deal.human_name} を削除します。よろしいですか？"}, class: :deal_deletion_link

app/views/deals/_detail.html.haml
.panel.panel-default
  = render partial: 'deals', locals: { deals: [deal], skip_deal_id: true }

app/views/deals/_edit_form.html.haml
= form_for @deal, :as => :deal, :url => deal_path(:id => @deal.id), :method => :patch, :html => {:id => 'deal_form'} do |f|
  = f.hidden_field(:year)
  = f.hidden_field(:month)
  = f.hidden_field(:day)
  - case @deal when Deal::General
    - if params[:complex] != 'true' && @deal.simple?
      - @deal.modify_errors_for_simple_form
      = render :partial => 'general_deal_form_contents', :locals => {:f => f, pattern_update_area: '#deal_forms'}
    - else
      - @deal.modify_errors_for_complex_form
      = render :partial => 'complex_deal_form_contents', :locals => {:f => f}
  - when Deal::Balance
    = render :partial => 'balance_deal_form_contents', :locals => {:f => f}
= error_messages_for :deal

app/views/deals/_general_deal_form_contents.html.erb
<div class="deal_patterns">
  <div style="display:none;" id="load_pattern_url"><%= @deal.new_record? ? new_complex_deal_path(:pattern_code => 'template_pattern_code') : deal_pattern_in_edit_path(:id => @deal.id, :pattern_code => 'template_pattern_code') %></div>
  <%= render :partial => 'shared/deal_patterns/search', :locals => {:update_area => pattern_update_area} %>
</div>
<div class="deal_fields">
  <%= f.text_field :summary, :size => "40", :tabindex => '10', :class => 'pattern_field' %>
  <%= f.hidden_field :summary_mode, :value => 'unify', :class => 'pattern_field' %>
  <div id="patterns"></div>
  <div class="entry">
    <% amount_field_proc, debtor_account_field_proc, creditor_account_field_proc = write_hiddens_and_get_simple_deal_procs(f) %>

    <%= render :partial => "general_deal_form_contents_#{bookkeeping_style? ? 'bookkeeping_style' : 'kozuchi_style'}",
      :locals => {
        :amount_field_proc => amount_field_proc,
        :debtor_account_field_proc => debtor_account_field_proc,
        :creditor_account_field_proc => creditor_account_field_proc,
        :tab_index => 10 # この次からはじまる
      }
    %>

    <%#= link_to 'パターン登録', '#', :id => 'add_pattern', class: %w(pull-right btn btn-default) %>
    &nbsp;<%= f.submit @deal.new_record? ? '記入' : '変更', :tabindex => "14", :class => 'submit btn btn-primary' %>
    <% if !@deal.new_record? %>
      <%= link_to '複数記入にする', {:action => 'edit', :id => @deal.id, :complex => true}, class: 'edit_deal', data: {deal_id: @deal.id} %>
    <% end %>
    <div style="clear:left;"></div>
  </div>
  <div style="clear:right;"></div>

  <%= javascript_tag do %>
  jQuery(document).ready(function($){
    $("input#deal_summary").observe_field(0.5, function() {
      $('#patterns').load('<%= deal_suggestions_path %>?keyword=' + encodeURIComponent(this.value))
    });

    $('a#add_pattern').click(function() {
      if ($('#deal_summary').val() == '') {
        alert('パターンを登録するには摘要が必要です。')
        return false
      } // end if
      $('#deal_pattern_frame').load('<%= deal_patterns_path %>', $(".pattern_field, input[name='authenticity_token']:first, input[name='utf8']:first").serializeArray())
      return false
    }) // end click
  })

  <% end %>
</div>

app/views/deals/_monthly_js.html.erb
<%= javascript_tag do %>
    function onGeneralDealSelectedFromGeneral(summary, amount, minus_account_id, plus_account_id, id, type, with_amount) {
        if(with_amount) {$('#deal_debtor_entries_attributes_0_amount').val(amount);}
        selectList('#deal_creditor_entries_attributes_0_account_id', minus_account_id);
        selectList('#deal_debtor_entries_attributes_0_account_id', plus_account_id);
        $('#deal_summary').val(summary);

        $('#deal_forms input.amount').focus();
    }
    function selectList(name, value) {
        $(name).val(value);
    }
    function onGeneralDealSelectedFromComplex(summary, amount, minus_account_id, plus_account_id, id, type, with_amount) {
        if($('#notice')){ $('#notice').hide();}

        var params = type == 'deal' ? 'load=' + id : 'pattern_id=' + id;
        params += '&with_amount=' + with_amount

        jQuery('#deal_forms').load('<%= url_for(:action => 'new_complex_deal', :controller => 'deals') %>', params, function() {
          displaySuggestionsForComplex()
        })
    }
    function fillForComplexDeal(id, type, with_amount) {
        if($('#notice')){ $('#notice').hide();}

        var params = type == 'deal' ? 'load=' + id : 'pattern_id=' + id;
        params += '&with_amount=' + with_amount

        jQuery('#deal_forms').load('<%= url_for(:action => 'new_complex_deal', :controller => 'deals') %>', params, function() {
          displaySuggestionsForComplex();
        })
    }
    function displaySuggestionsForComplex() {
        jQuery('#patterns').load('<%= deal_suggestions_path(:from => 'complex_deal') %>', 'keyword=' + encodeURIComponent($('#deal_summary').val()))
    }
<% end %>